export const translations = {
  en: {
    // Dashboard Keys
    dashboard: "CASHIER DASHBOARD",
    bet: "BET",
    sold: "Sold Cartelas",
    print: "PRINT CARTELAS",
    select: "Select Cartela to Sell",
    sell: "SELL SELECTED",
    sellButton: "SELL",
    start: "START GAME",
    finance: "FINANCE DETAILS",
    qr: "PLAYER QR CODE",
    winner: "WINNER",
    noCards: "No cards sold yet.",
    netIncome: "Net Income",
    resetGame: "Reset Game",
    package: "Package",
    insufficient: "Insufficient",
    cashier: "Cashier",
    robotVoice: "Robot Voice",
    amharicVoice: "Amharic Voice",
    scanToChooseCards: "SCAN TO CHOOSE CARDS",
    qrInstructions: "Players scan this QR code on their mobile phones to choose 1 or more Cartela numbers (1–150).",
    close: "Close",
    typeCartelaPlaceholder: "Type # & press Enter...",

    // Authentication Keys
    username: "Username",
    password: "Password",
    login: "LOGIN",
    language: "Language",

    // Game Keys
    cardIdPlaceholder: "CARD ID",
    verifyCard: "VERIFY CARD",
    play: "▶ PLAY",
    pause: "⏸ PAUSE",
    gamePrize: "GAME PRIZE",
    currentBall: "CURRENT BALL",
    ready: "READY",
    waitingToBegin: "Waiting for the game sequence to begin...",
    dashboardBtn: "← DASHBOARD",
    tvBroadcast: "TV BROADCAST",
    resetBoard: "RESET",
    soundOn: "SOUND ON",
    soundOff: "SOUND OFF"
  },

  am: {
    // Dashboard Keys
    dashboard: "የካሽየር መቆጣጠሪያ",
    bet: "ውርርድ",
    sold: "የተሸጡ ካርቴላዎች",
    print: "ካርቴላዎችን አትም",
    select: "የሚሸጥ ካርቴላ ይምረጡ",
    sell: "የተመረጠውን ሽጥ",
    sellButton: "ሽጥ",
    start: "ጨዋታ ጀምር",
    finance: "የፋይናንስ ዝርዝር",
    qr: "የተጫዋች QR ኮድ",
    winner: "አሸናፊ",
    noCards: "እስካሁን ምንም ካርቴላ አልተሸጠም።",
    netIncome: "የተጣራ ገቢ",
    resetGame: "ጨዋታውን ድገም",
    package: "ፓኬጅ",
    insufficient: "በቂ አይደለም",
    cashier: "ካሸር",
    robotVoice: "የሮቦት ድምፅ",
    amharicVoice: "የአማርኛ ድምፅ",
    scanToChooseCards: "ካርቴላ ለመምረጥ ስካን ያድርጉ",
    qrInstructions: "ተጫዋቾች ከ1-150 ያሉትን የካርቴላ ቁጥሮች በስልካቸው ለመምረጥ ይህንን QR ኮድ ስካን ያድርጉ።",
    close: "ዝጋ",
    typeCartelaPlaceholder: "ቁጥር ጽፈው Enter ይጫኑ...",

    // Authentication Keys
    username: "የተጠቃሚ ስም",
    password: "የይለፍ ቃል",
    login: "ግባ",
    language: "ቋንቋ",

    // Game Keys
    cardIdPlaceholder: "የካርድ መለያ (ID)",
    verifyCard: "ካርዱን አረጋግጥ",
    play: "▶ ጀምር",
    pause: "⏸ ቁም",
    gamePrize: "የጨዋታው ሽልማት",
    currentBall: "የአሁኑ ኳስ",
    ready: "ዝግጁ",
    waitingToBegin: "የጨዋታው ቅደም ተከተል እስኪጀምር በመጠበቅ ላይ...",
    dashboardBtn: "← ወደ መቆጣጠሪያው",
    tvBroadcast: "የቲቪ ስርጭት",
    resetBoard: "እንደገና ማስጀመር",
    soundOn: "ድምፅ አብራ",
    soundOff: "ድምፅ ዝጋ"
  },

  om: {
    // Dashboard Keys
    dashboard: "Daashboordii Kaashiyeeraa",
    bet: "Sharafa",
    sold: "Kaartota Gurguraman",
    print: "Kaartota Maxxansi",
    select: "Kaartaa Gurgurtaaf Filadhu",
    sell: "Kan Filatame Gurguri",
    sellButton: "Gurguri",
    start: "Tapha Jalqabi",
    finance: "Tarree Faayinaansii",
    qr: "QR Koodii Taphataa",
    winner: "Mo'ataa",
    noCards: "Kaartaan hanga ammaatti hin gurguramne.",
    netIncome: "Galii Qulqulluu",
    resetGame: "Tapha Haaressi",
    package: "Paakeejii",
    insufficient: "Gahaa miti",
    cashier: "Kaashiyara",
    robotVoice: "Sagalee Roobootii",
    amharicVoice: "Sagalee Amaaraa",
    scanToChooseCards: "Kaarteelaa Filachuuf Iskaan Godhaa",
    qrInstructions: "Taphattonni lakkoofsa Kaarteelaa (1–150) bilbila isaaniitiin filachuuf QR koodii kana iskaan godhu.",
    close: "Cufi",
    typeCartelaPlaceholder: "Lakkoofsa galchi Enter cuqqaali...",

    // Authentication Keys
    username: "Maqaa Fayyadamaa",
    password: "Jecha Darbii",
    login: "Seeni",
    language: "Afaan",

    // Game Keys
    cardIdPlaceholder: "ID KAARTAA",
    verifyCard: "KAARTAA MIRKANEESSI",
    play: "▶ JALQABI",
    pause: "⏸ DHAABI",
    gamePrize: "BADHAASA TAPHAAN",
    currentBall: "KUBBAA AMMAA",
    ready: "QOPHIIDHA",
    waitingToBegin: "Tartiibni taphaa hanga jalqabutti eegaa...",
    dashboardBtn: "← DAASHBOORDII",
    tvBroadcast: "SAB-AAMAA TV",
    resetBoard: "HAAROMSI",
    soundOn: "SAGALEE BILISA",
    soundOff: "SAGALEE CUFI"
  }
};